apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k732e0z7n-java-quarkus
  janus-idp.io/tekton: k732e0z7n-java-quarkus
  backstage.io/kubernetes-id: k732e0z7n-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k732e0z7n-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
